# Copyright 2026 Dynatrace LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: "Configure"
description: "Configure build environment"

runs:
  using: "composite"
  steps:
    - name: "Configure"
      shell: bash
      run: >-
        docker run -i --rm
        -w ${{ github.workspace }}
        --user=$(id -u):$(id -g)
        -v /home/runner:/home/runner
        -v /etc/passwd:/etc/passwd
        nettracer-build:latest
        cmake
        -S .
        -B build
        -DCMAKE_BUILD_TYPE=Release
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DKERNEL_VERSION=4.15.0-101-generic
